accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/',views.Logout.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('signupdone/',views.SignUpDone.as_view(),name='signupdone'),
    path('signupcomplete/<token>/',views.SignUpComplete.as_view(),name='signupcomplete'),
    path('edit/', views.user_edit, name='edit'),
    path('delete/<slug:username>/', views.AccountDelete.as_view(), name='delete'),
    path('password/change/', views.PasswordChange.as_view(), name='password_change'),
    path('password/change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
]

groups/urls.py
from django.urls import path
from . import views


app_name = 'groups'

urlpatterns = [
    path('',views.GroupList.as_view(),name='group_list'),#部活動メンバーの一覧表示
    path('ajax_post_add/',views.GroupRequestAdd,name='ajax_post_add'),
    path('<str:group_id>/request/',views.GroupDetail.as_view(),name='group_detail'),
    path('create/',views.GroupCreate.as_view(),name='group_create')
]

person/urls.py
from django.urls import path,include
from . import views


app_name = 'person'

urlpatterns = [
    path('',views.Home.as_view(),name='home'),#部活動メンバーの一覧表示
    path('<slug:username>/myaccount/', views.MyAccount.as_view(), name='myaccount'),  # 該当アカウント
    path('members/', views.Menbers.as_view(), name='members'),  # members
    path('members/approval/',views.member_approval,name='member_approval'),
    path('agreement/',views.Agreement.as_view(),name='agreement'),
]

person_manager/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
import person



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('person.urls')),
    path('accounts/', include('accounts.urls')),
    path('records/',include('records.urls')),
    path('schedules/',include('schedules.urls')),
    path('groups/',include('groups.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm, PasswordChangeForm,PasswordResetForm,SetPasswordForm
from django import forms
from django.contrib.auth import get_user_model
from . import models
from person.mixins import BaseModelForm,BaseForm
from django.utils.translation import gettext_lazy as _


User = get_user_model()

class SignUpForm(BaseForm,UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        fields = ('email','username')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email


class ProfileUpdateForm(BaseModelForm):
    """ProfileModelアップデートフォーム"""
    class Meta:
        model = models.UserProfile
        fields = ('first_name','last_name','birthday','user_image',)

        widgets = {
          'first_name': forms.TextInput(attrs={'class': 'form-control'}),
          'last_name': forms.TextInput(attrs={'class': 'form-control'}),
          'birthday': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
          'user_image': _('プロフィール画像')
        }


class UserUpdateForm(BaseModelForm):
    #Userモデルにprofileモデルを入れる
    # formset_class = ProfileFormSet
    class Meta:
        model = User
        fields = ('username',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class ProfileForm(BaseModelForm):

    class Meta:
        model = models.UserProfile
        fields = ('first_name','last_name','birthday',)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['birthday'].widget = forms.SelectDateWidget(years=[x for x in range(1990, 2030)]) # 引数にattrs={'class': 'form-control'}も可能

class LoginForm(BaseForm,AuthenticationForm):
    def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)
      for field in self.fields.values():
        field.widget.attrs['class'] = 'form-control'
        field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる


class MyPasswordChangeForm(BaseForm,PasswordChangeForm):
    """パスワード変更フォーム"""

    def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)
      for field in self.fields.values():
        field.widget.attrs['class'] = 'form-control'
        field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる

class MyPasswordResetForm(BaseForm,PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)
      for field in self.fields.values():
        field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(BaseForm,SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)
      for field in self.fields.values():
        field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.views import LoginView,PasswordChangeView,LogoutView, PasswordChangeDoneView, PasswordResetView,\
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login as auth_login,get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.template.loader import render_to_string
from django.http import HttpResponseBadRequest
from django.conf import settings
from django.contrib.auth.decorators import login_required
from . import forms
from . import models
from . import mixins
from django.core.mail import send_mail

 # ログインしていないと入れない
User = get_user_model()


class Login(LoginView):
    form_class = forms.LoginForm
    template_name = 'accounts/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    template_name = 'accounts/login.html'


class SignUp(generic.CreateView):
    """account作成"""
    template_name = "accounts/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy('')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        #domeinの取得
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }
        #templateを呼び出す
        subject = render_to_string('mail/create/subject.txt', context)
        message = render_to_string('mail/create/message.txt', context)

        send_mail(subject , message, 'apasn@apasn.com', [user.email], fail_silently=False)

        # user.email_user(subject, message)
        return redirect('accounts:signupdone')

class SignUpDone(generic.TemplateView):
    """ユーザー仮登録"""
    template_name = 'accounts/signupdone.html'

class SignUpComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""

    template_name = 'accounts/signupcomplete.html'
    #settingsインスタンスのactivation_timeout_secondsに時間を設定している
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token,max_age=self.timeout_seconds)
        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    models.UserProfile.objects.create(user=user)
                    auth_login(request, user)
                    #profile編集へ
                    return redirect('accounts:edit')
        return HttpResponseBadRequest()

#ユーザーアカウント情報アップデート
@login_required
def user_edit(request):
  if request.method == 'POST':
    form = forms.UserUpdateForm(request.POST, instance=request.user)
    subform = forms.ProfileUpdateForm(request.POST,request.FILES, instance=request.user.userprofile)

    if all([form.is_valid(), subform.is_valid()]):
      user = form.save()
      profile = subform.save()
      return redirect('person:myaccount', username=request.user)
  else:
    form = forms.UserUpdateForm(instance=request.user)
    subform = forms.ProfileUpdateForm(instance=request.user.userprofile)
  return render(request, 'accounts/accounts_edit.html', {
    'form': form,
    'subform': subform,
  })


class AccountDelete(mixins.OnlyYouMixin,generic.DeleteView):
    template_name = "accounts/delete.html"
    success_url = reverse_lazy("accounts:login")
    model = User
    slug_field = 'username'
    slug_url_kwarg = 'username'


class PasswordChange(LoginRequiredMixin,PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = forms.MyPasswordChangeForm
    success_url = reverse_lazy('accounts:password_change_done')
    template_name = 'accounts/password_change.html'


class PasswordChangeDone(LoginRequiredMixin,PasswordChangeDoneView):
    """パスワード変更しました"""
    template_name = 'accounts/password_change_done.html'


class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'mail/accounts/password_reset/subject.txt'
    email_template_name = 'mail/accounts/password_reset/message.txt'
    template_name = 'accounts/password_reset_form.html'
    form_class = forms.MyPasswordResetForm
    success_url = reverse_lazy('accounts:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'accounts/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = forms.MySetPasswordForm
    success_url = reverse_lazy('accounts:password_reset_complete')
    template_name = 'accounts/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定後ページ"""
    template_name = 'accounts/password_reset_complete.html'

templates/accounts/accounts_edit.html
{% extends "commons/base.html" %}
{% block headertitle %} ACCOUNTS{% endblock %}
{% block content %}

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
          <div class="text-center col-lg-6 col-md-6 col-sm-10 mx-auto">
          <div class="form-group">
            {{ form.username.label }}
            {{ form.username }}
          </div>
            <div class="form-group">
              {{ subform.user_image.label_tag }}
              <div class="custom-file form-group mb-3">
              {{ subform.user_image }}
              </div>
              </div>
              <div class="form-group mt-5">
              {{ subform.last_name.label_tag }}
              {{ subform.last_name }}
              </div>
              <div class="form-group">
              {{ subform.first_name.label_tag }}
              {{ subform.first_name }}
              </div>
              <div class="form-group">
              {{ subform.birthday.label_tag }}
              {{ subform.birthday }}


            </div>


            <button type="submit" class="fadeIn fourth btn btn-light">Submit</button>
            </div>
        </form>
<div class="row">
        <div class="col-lg-12 col-sm-12 text-center">
          <button type="button" onclick="location.href='{% url 'accounts:delete' username=user %}'" class="btn btn-light">退会する</button>
          <button type="button" onclick="location.href='{% url 'accounts:logout' %}'" class="btn btn-light">logout</button>
          <button type="button" onclick="location.href='{% url 'accounts:password_change' %}'" class="btn btn-light">パスワード変更</button>
        </div>
        </div>
{% endblock %}

templates/accounts/delete.html
{% extends "commons/base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block title %}メール登録{% endblock %}
{% block content %}
<form role="form" method="post">
  {% csrf_token %}
  <p>あなたのアカウント「@{{ user.username }}」を、本当に削除してもよろしいですか？</p>

  <button type="submit" class="button is-danger">削除</button>
  <a href="javascript:void(0);" onclick="window.history.back();" class="button is-text">キャンセル</a>
</form>
{% endblock %}

templates/accounts/login.html
{% extends "commons/account_base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block title %}Login{% endblock %}
{% block link %}<link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">{% endblock %}

{% block content %}
<div class="text-center">
<form class="form-signin" action="" method="POST">
      <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      {% csrf_token %}
      {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
      {% endif %}
      {{ form.username.label }}
      {{ form.username }}
      {{ form.password.label }}
      {{ form.password }}
      <div class="checkbox mb-3">
        <a class="btn text-dark" href="{% url 'accounts:password_reset' %}">Forgot Password?</a>
        <a class="btn text-dark" href="{% url 'accounts:signup' %}">アカウント作成</a>
      </div>
      <button  type="submit" class="fadeIn fourth btn btn-light">ログイン</button>
      <input type="hidden" name="next" value="{{ next }}" />
    <p class="mt-5 mb-3 text-muted"><a class=" text-dark" href="{% url 'person:agreement' %}">利用規約</a></p>
      <p class="mt-5 mb-3 text-muted">&copy; 2019-2020</p>
    </form>
</div>
{% endblock %}


{% block extrajs %}{% endblock %}

templates/accounts/logout.html
{% extends "commons/account_base.html" %}

{% block title %}Logout{% endblock %}

{% block content %}
<h1>Logged Out</h1>
<p>Thanks for spending some quality time with the Web site today.</p>
<p><a href="{% url 'accounts:login' %}">Log in again</a></p>
{% endblock %}

templates/accounts/password_change.html
{% extends "commons/base.html" %}
{% load static %}
{% block content %}
<div class="text-center col-lg-5 col-md-6 col-sm-10 mx-auto">
<form action="" method="POST">

    {{ form.non_field_errors }}

    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}

    {% csrf_token %}
    <button type="submit" class="btn btn-light  btn-lg">送信</button>
</form>
  </div>





<!--<form class="form-signin" action="" method="POST">-->
      <!--<img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">-->
      <!--<h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>-->
      <!--{% csrf_token %}-->
      <!--{{ form.non_field_errors }}-->
      <!--{% for field in form %}-->
      <!--<div class="form-groups">-->
        <!--<label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>-->
        <!--{{ field }}-->
        <!--{{ field.errors }}-->
        <!--{% endfor %}-->
      <!--</div>-->
    <!--</form>-->

{% endblock %}

templates/accounts/password_change_done.html
{% extends "commons/base.html" %}
{% load static %}
{% block title %}パスワード変更完了{% endblock %}
{% block content %}
<p>
    パスワードを変更しました。<br>
</p>
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends "commons/account_base.html" %}
{% load static %}

{% block title %}パスワード再設定完了{% endblock %}

{% block content %}
<form action="" method="POST">
  <div class="text-center col-lg-4 mx-auto col-md-6 col-sm-7 col-8">
    <h2 class="h3 mb-3 font-weight-normal lead">パスワード再設定を完了しました。</h2>
    <a class="btn text-dark btn-block" href="{% url 'accounts:login' %}">ログイン</a>
  </div>
</form>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends "commons/account_base.html" %}
{% load static %}

{% block title %}パスワード変更確認{% endblock %}

{% block content %}
<form action="" method="POST">
  <div class="text-center col-lg-4 mx-auto col-md-6 col-sm-7 col-">
      {{ form.non_field_errors }}
      {% for field in form %}
      <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
          {{ field }}
          {{ field.errors }}
      </div>
      {% endfor %}
      {% csrf_token %}
      <button type="submit" class="btn btn-light  btn-block">送信</button>
    </div>
</form>
{% endblock %}

templates/accounts/password_reset_done.html
{% extends "commons/account_base.html" %}
{% load static %}


{% block title %}
  パスワードリセット（メール送信）
{% endblock %}

{% block content %}
<form action="" method="POST">
  <div class ="text-center col-lg-7 mx-auto col-md-6 col-sm-7 col-8">
    <h1 class="h3 mb-3 font-weight-normal lead mb-5">
      <p>
      メールを送信しました。
      </p>

      メールに記載されているリンクから
      <br />パスワードの再設定を行ってください。
    </h1>
    <button type="button" onclick="location.href='{% url 'accounts:login' %}'" class="btn btn-light">ログイン画面</button>
  </div>
</form>
{% endblock %}

templates/accounts/password_reset_form.html
{% extends "commons/account_base.html" %}
{% load static %}


{% block title %}パスワード変更{% endblock %}
<!--{% block link %}<link rel="stylesheet" href="{% static 'accounts/css/.css' %}">{% endblock %}-->
{% block content %}
<form class="form-password-reset " action="" method="POST">
  {% csrf_token %}
  <div class ="text-center col-lg-4 mx-auto col-md-6 col-sm-7 col-8">
  <h2 class="h3 mb-3 font-weight-normal lead mt-5">パスワードの変更</h2>
  <h2 class="h3 mb-3 font-weight-normal lead">メールアドレスを入力してください。</h2>
    {{ form.non_field_errors }}
    <div class="form-group">
        {{ form.email.label }}
        {{ form.email }}
        {{ form.errors }}
    </div>
    <div class="mb-3">
        <a class="btn text-dark" href="{% url 'accounts:signup' %}">アカウント作成</a>
      </div>
        <button type="submit" class="btn btn-light mb-5">送信</button>
    </div>
</form>

{% endblock %}

templates/accounts/profileform.html
{% extends "commons/account_base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block title %}プロフィールフォーム{% endblock %}
{% block content %}
<form method="POST" action="">
  <div class ="text-center col-lg-7 mx-auto col-md-6 col-sm-7 col-8">
    {% csrf_token %}
    <div class="form-group">
    {{form.first_name.label_tag}}
    {{form.first_name}}
      </div>
    <div class="form-group">
    {{form.last_name.label_tag}}
    {{form.last_name}}
    </div>
      <div class="form-group">
    {{form.birthday.label_tag}}
    {{form.birthday}}
      </div>
    <input class="btn btn-light" type="submit" value="submit">
  </div>
</form>

{% endblock %}

templates/accounts/signup.html
{% extends "commons/account_base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block title %}メール登録{% endblock %}
{% block content %}
<form action="" method="POST">

    {% csrf_token %}
  <div class ="text-center col-lg-4 mx-auto col-md-6 col-sm-7 col-8">
    {{ form.non_field_errors }}
     <small class="text-muted">※ユーザーネームはアルファベットと数字のみです。</small>
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>

        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-light">送信</button>
  </div>
</form>
{% endblock %}

templates/accounts/signupcomplete.html
<p>
    本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'accounts:login' %}">ログイン</a>
</p>

templates/accounts/signupdone.html
{% extends "commons/account_base.html" %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% block title %}メール送信完了！{% endblock %}
{% block content %}
<div class ="text-center col-lg-8 mx-auto col-md-9 col-sm-10 col-8">
  <h1 class="h3 mb-3 font-weight-normal lead">会員登録確認メールを送信しました。<br>まだ、会員登録は完了していません。
    <br>
   確認メールに記載されているリンクから本登録を行ってください。</h1>
</div>
{% endblock %}