groups/urls.py
from django.urls import path
from . import views


app_name = 'groups'

urlpatterns = [
    path('',views.GroupList.as_view(),name='group_list'),#部活動メンバーの一覧表示
    path('ajax_post_add/',views.GroupRequestAdd,name='ajax_post_add'),
    path('<str:group_id>/request/',views.GroupDetail.as_view(),name='group_detail'),
    path('create/',views.GroupCreate.as_view(),name='group_create')
]

person_manager/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
import person



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('person.urls')),
    path('accounts/', include('accounts.urls')),
    path('records/',include('records.urls')),
    path('schedules/',include('schedules.urls')),
    path('groups/',include('groups.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

records/urls.py
from django.urls import path,include
from . import views


app_name = 'records'

urlpatterns = [
    path('recordcreate/',views.RecordCreate.as_view(),name='recordcreate'),
    path('title_create/',views.title_create,name='title_create'),
    path('<id>/', views.RcordDetail.as_view(), name='record_detail'),
    path('<id>/edit/', views.RecordDetailEdit.as_view(), name='record_detail_edit'),
    path('<id>/delete/',views.RecordDetailDelete.as_view(),name='record_detail_delete'),

]

records/models.py
from django.db import models
from accounts.models import User
from django.utils import timezone
from groups.models import Group
from django.utils.translation import gettext_lazy as _
import uuid
import os
from django.dispatch import receiver
from datetime import datetime

#RecordImageファイル名UUID変更関数
def get_file_path(instance, filename):
  if not 'records/default.jpg' == filename:
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('records/', filename)

class UserRecordTitle(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_record_title = models.CharField(_('レコードタイトル'), max_length=30,)

    def __str__(self):
        return self.user_record_title


class UserRecordContent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True)
    user_record_title = models.ForeignKey(UserRecordTitle,on_delete=models.CASCADE,blank=True,null=True)
    user_record_image = models.ImageField(_('写真'),upload_to=get_file_path,blank=True,default='records/default.jpg')
    user_record_content = models.CharField(_('内容'), max_length=300)
    user_record_elapsed_time = models.DurationField(_('経過時間'))
    user_record_time = models.DateTimeField(_('記録時間'), default=timezone.now)
    def __str__(self):
        return self.user_record_content


@receiver(models.signals.post_delete, sender=UserRecordContent)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if not 'records/default.jpg' == instance.user_record_image:
        if os.path.isfile(instance.user_record_image.path):
            os.remove(instance.user_record_image.path)

@receiver(models.signals.pre_save, sender=UserRecordContent)
def auto_delete_file_on_change(sender, instance, **kwargs):
  """
  Deletes old file from filesystem
  when corresponding `MediaFile` object is updated
  with new file.
  """
  if not instance.pk:
    return False

  try:
    old_file = sender.objects.get(pk=instance.pk).user_record_image
  except sender.DoesNotExist:
    return False

  new_file = instance.user_record_image

  if not old_file == new_file:
     if not 'records/default.jpg' == old_file:
      if os.path.isfile(old_file.path):
        os.remove(old_file.path)



#
# #TODO:UserRecordとまとめた方がいいのか検証後実装
# class GroupRecordTitle(models.Model):
#     group = models.ForeignKey(Group, on_delete=models.CASCADE,null=True)
#     group_record_title = models.CharField(_('練習メニュー'), max_length=30,editable=True)
#     def __str__(self):
#         return self.group_record_title
# #TODO:GRoupRecordTitleと同じ
# class GroupRecordContent(models.Model):
#     group = models.ForeignKey(Group, on_delete=models.CASCADE)
#     group_record_title = models.ForeignKey(GroupRecordTitle,on_delete=models.CASCADE)
#     group_record_image = models.ImageField(upload_to=get_file_path, blank=True, default='records/default')
#     group_record_content= models.CharField(_('練習記録'), max_length=300)
#     group_record_elapsed_time = models.DateTimeField(_('経過時間'))
#     group_record_time = models.DateTimeField(_('記録時間'), default=timezone.now)
#
#     def __str__(self):
#         return self.group_record_content

records/forms.py
from django import forms
from . import models
from person.mixins import BaseModelForm
import bootstrap_datepicker_plus as datetimepicker
from django.utils.translation import gettext_lazy as _


class RecordTitleCreateForm(BaseModelForm):
    class Meta:
        model = models.UserRecordTitle
        fields = ('user_record_title',)
        widgets = {
            'user_record_title': forms.TextInput(attrs={'class': 'form-control'}),}


class RecordCreateForm(BaseModelForm):
    class Meta:
        model = models.UserRecordContent
        fields = ('user_record_title','user_record_image','user_record_content',
                  'user_record_elapsed_time','user_record_time',)
        widgets = {
            'user_record_content': forms.TextInput(attrs={'class': 'form-control'}),}
        labels = {
          'user_record_title': _('タイトル'),
          'user_record_content': _('内容・ひとこと'),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(RecordCreateForm,self).__init__(*args, **kwargs)
        self.fields['user_record_title'].queryset = models.UserRecordTitle.objects.filter(user=user)
        self.fields['user_record_title'].widget.attrs = {'class':'form-control'}
        self.fields['user_record_elapsed_time'].widget = datetimepicker.TimePickerInput(
                format='%H:%M',
                attrs={'readonly': 'true'},
                options={
                    'locale': 'ja',
                    'ignoreReadonly': True,
                    'allowInputToggle': True,
                })
        self.fields['user_record_time'].widget = datetimepicker.DateTimePickerInput(
                format='%Y-%m-%d %H:%M',
                attrs={'readonly': 'true'},
                options={
                    'locale': 'ja',
                    'dayViewHeaderFormat': 'YYYY年 MMMM',
                    'ignoreReadonly': True,
                    'allowInputToggle': True,
                }
            )

class RecordDetailEditForm(BaseModelForm):
    class Meta:
        model = models.UserRecordContent
        fields = ('user_record_image','user_record_title','user_record_content',
                  'user_record_elapsed_time','user_record_time')
        widgets = {
            'user_record_content': forms.TextInput(attrs={'class': 'form-control'}), }
        labels = {
          'user_record_title': _('タイトル'),
        }


    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(RecordDetailEditForm, self).__init__(*args, **kwargs)
        self.fields['user_record_title'].queryset = models.UserRecordTitle.objects.filter(user=user)
        self.fields['user_record_title'].widget.attrs = {'class':'form-control'}
        self.fields['user_record_elapsed_time'].widget = datetimepicker.TimePickerInput(
            format='%H:%M',
            attrs={'readonly': 'true'},
            options={
                'locale': 'ja',
                'ignoreReadonly': True,
                'allowInputToggle': True,
              })
        self.fields['user_record_time'].widget = datetimepicker.DateTimePickerInput(
            format='%Y-%m-%d %H:%M',
            attrs={'readonly': 'true'},
            options={
                'locale': 'ja',
                'dayViewHeaderFormat': 'YYYY年 MMMM',
                'ignoreReadonly': True,
                'allowInputToggle': True,
            })

records/views.py
from django.views.generic import CreateView,UpdateView,TemplateView,DetailView,DeleteView
from django.urls import reverse_lazy,reverse
from django.shortcuts import get_object_or_404,render,redirect,HttpResponse,HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from . import models
from . import forms
from accounts.models import UserBelong
from django.contrib import messages
from . import mixins


User = get_user_model()

class RecordCreate(LoginRequiredMixin,CreateView):
    """レコード作成"""
    model = models.UserRecordContent
    form_class = forms.RecordCreateForm
    template_name = 'records/user_record_create.html'
    success_url = reverse_lazy('person:home')

    def get_context_data(self, **kwargs):
      context_data = super(RecordCreate, self).get_context_data(**kwargs)
      context_data['title_create'] = forms.RecordTitleCreateForm

      return context_data

    def get_form_kwargs(self):
      kwargs = super(RecordCreate, self).get_form_kwargs()
      kwargs['user'] = self.request.user
      return kwargs

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        try:
          form.instance.group = UserBelong.objects.get(user=user).group
        except:
          pass
        return super().form_valid(form)
@login_required
@require_http_methods(["POST"])
def title_create(request):
    """レコードタイトル作成"""
    title_name = request.POST.get('user_record_title_name')
    models.UserRecordTitle.objects.create(user=request.user,user_record_title_name=title_name)
    return HttpResponseRedirect(reverse('records:recordcreate'))


class RcordDetail(LoginRequiredMixin,DetailView):
    """レコード詳細"""
    template_name = 'records/user_record_detail.html'
    model = models.UserRecordContent
    pk_url_kwarg = 'id'

class RecordDetailEdit(mixins.OnlyRecordEditMixin,UpdateView):
    """レコード編集"""
    template_name = 'records/user_record_edit.html'
    model = models.UserRecordContent
    pk_url_kwarg = 'id'
    form_class = forms.RecordDetailEditForm
    success_url = reverse_lazy('person:home')

    def get_form_kwargs(self):
      #formにuser情報を渡す
      kwargs = super(RecordDetailEdit, self).get_form_kwargs()
      kwargs['user'] = self.request.user
      return kwargs

    def form_valid(self, form):
      #削除されていた場合はデフォルトを適用する
      if not form.instance.user_record_image:
        form.instance.user_record_image = 'records/default.jpg'
      return super().form_valid(form)

class RecordDetailDelete(LoginRequiredMixin,DeleteView):
    """レコード削除"""
    template_name = 'records/user_record_delete.html'
    model = models.UserRecordContent
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('person:home')

templates/records/user_record_create.html
{% extends "commons/base.html" %}
{% load static %}

{% block title %}記録作成{% endblock %}

{% block headertitle %} RECORDS{% endblock %}
{% block link %} <link rel="stylesheet" href="{% static 'records/css/user_record_create.css' %}">{% endblock %}
{% block content %}
{{ form.media }}
<h1 class="h4 lead font-weight-bold">レコードのタイトルを作成しよう！</h1>
<div class="border-top mt-3">
  <div class="mt-2 form-group text-center">
<form method="post" action="{% url 'records:title_create' %}">
  {% csrf_token %}
  <div class="form-group">
  {{ title_create }}
  </div>
  <input class="btn btn-light mt-3" type="submit" value="作成">
</form>
    </div>
</div>

<div class="mt-4">
<h1 class="h4 lead font-weight-bold">レコードを投稿しよう！</h1>
<div class="border-top mt-3">
  <div class="mt-2 form-group text-center">
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}


{{form.user_record_image.label_tag}}
  <div class="custom-file form-group">
  {{form.user_record_image}}
</div>

  <div class="form-group">
    {{form.user_record_title.label}}
    {{form.user_record_title}}
    </div>
  <div class="form-group">
    {{form.user_record_content.label_tag}}<small class="text-muted">※入力してね！</small>
    {{form.user_record_content}}
  </div>
  <div class="form-group">
    {{form.user_record_elapsed_time.label_tag}}<small class="text-muted">※入力してね！</small>
    {{form.user_record_elapsed_time}}
    </div>
  <div class="form-group">
    {{form.user_record_time.label_tag}}
    {{form.user_record_time}}
  </div>
    <input class="btn btn-light mt-3" type="submit" value="投稿">
</form>
    </div>
</div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

templates/records/user_record_delete.html
{% extends "commons/base.html" %}
{% load static %}

{% block title %}プロフィールフォーム{% endblock %}
{% block content %}
<form method="POST" action="">
  <div class ="text-center col-lg-7 mx-auto col-md-6 col-sm-7 col-8">
    {% csrf_token %}
    <div class="form-group">
    <p>本当に "{{ object }}" を削除しますか?</p>
      </div>

    <input class="btn btn-light" type="submit" value="submit">
  </div>
</form>

{% endblock %}

templates/records/user_record_detail.html
{% extends "commons/base.html" %}
{% load static %}

{% block title %}メニュー{% endblock %}

{% block headertitle %}{% endblock %}

{% block link %}<link rel="stylesheet" href="{% static 'records/css/detail.css' %}">{% endblock %}

{% block content %}
<div class="detail-container">
        <!-- Three columns of text below the carousel -->
        <div class=" mt-5 mx-auto">
          <div class="card">
            <div class="d-inline-block">
            <h1 class="h3 font-weight-normal d-inline-block">{{ userrecordcontent.user }}</h1>
              {% if userrecordcontent.user == user %}
            <a class="text-dark d-inline-block float-right " href="{% url 'records:record_detail_edit' userrecordcontent.id %}"><i class="fas fa-cogs d-inline"></i></a>
              {% endif %}
            </div>
            <img class="card-img-top img-fluid " style="width: 100%; height: 50%;" src="{{ userrecordcontent.user_record_image.url }}" alt="Generic placeholder image" >
             

            <div class="card-body text-center">


              <p>{{ userrecordcontent.user_record_content }}</p>
              {% if userrecordcontent.user_record_title  %}
              <p>{{ userrecordcontent.user_record_title }}</p>
              {% endif %}
              <small class="text-muted">{{ userrecordcontent.user_record_elapsed_time }}</small>
              <small class="text-muted">{{ userrecordcontent.user_record_time }}</small>
              </div>
          </div><!-- /.col-lg-4 -->
    </div>
  </div>
{% endblock %}

{% block scripts %}
{% endblock %}

templates/records/user_record_edit.html
{% extends "commons/base.html" %}
{% load static %}

{% block title %}プロフィールフォーム{% endblock %}
{% block content %}
{{ form.media }}
<div class="text-center">
<form method="POST" action="" enctype="multipart/form-data">
  <div class ="text-center col-lg-7 mx-auto col-md-6 col-sm-7 col-8">
    {% csrf_token %}
    <div class="form-group">
    {{ form.user_record_title.label_tag }}
    {{ form.user_record_title }}
      </div>
    <div class="form-group">
      {{ form.user_record_image.label_tag }}
      {{ form.user_record_image }}
    </div>
      <div class="form-group">
        {{ form.user_record_content.label_tag }}
        {{ form.user_record_content }}
      </div>
    <div class="form-group">

      {{ form.user_record_elapsed_time.label_tag }}
      {{ form.user_record_elapsed_time }}
    </div>
    <div class="form-group">
      {{ form.user_record_time.label_tag }}
      {{ form.user_record_time }}
    </div>


    <input class="btn btn-light" type="submit" value="submit">
  </div>
</form>

<a class="btn btn-light" href="{% url 'records:record_detail_delete' userrecordcontent.id %}">削除</a>
</div>
{% endblock %}