accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/',views.Logout.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('signupdone/',views.SignUpDone.as_view(),name='signupdone'),
    path('signupcomplete/<token>/',views.SignUpComplete.as_view(),name='signupcomplete'),
    path('edit/', views.user_edit, name='edit'),
    path('delete/<slug:username>/', views.AccountDelete.as_view(), name='delete'),
    path('password/change/', views.PasswordChange.as_view(), name='password_change'),
    path('password/change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
]

groups/urls.py
from django.urls import path
from . import views


app_name = 'groups'

urlpatterns = [
    path('',views.GroupList.as_view(),name='group_list'),#部活動メンバーの一覧表示
    path('ajax_post_add/',views.GroupRequestAdd,name='ajax_post_add'),
    path('<str:group_id>/request/',views.GroupDetail.as_view(),name='group_detail'),
    path('create/',views.GroupCreate.as_view(),name='group_create')
]

person/urls.py
from django.urls import path,include
from . import views


app_name = 'person'

urlpatterns = [
    path('',views.Home.as_view(),name='home'),#部活動メンバーの一覧表示
    path('<slug:username>/myaccount/', views.MyAccount.as_view(), name='myaccount'),  # 該当アカウント
    path('members/', views.Menbers.as_view(), name='members'),  # members
    path('members/approval/',views.member_approval,name='member_approval'),
    path('agreement/',views.Agreement.as_view(),name='agreement'),
]

person_manager/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
import person



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('person.urls')),
    path('accounts/', include('accounts.urls')),
    path('records/',include('records.urls')),
    path('schedules/',include('schedules.urls')),
    path('groups/',include('groups.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

records/urls.py
from django.urls import path,include
from . import views


app_name = 'records'

urlpatterns = [
    path('recordcreate/',views.RecordCreate.as_view(),name='recordcreate'),
    path('title_create/',views.title_create,name='title_create'),
    path('<id>/', views.RcordDetail.as_view(), name='record_detail'),
    path('<id>/edit/', views.RecordDetailEdit.as_view(), name='record_detail_edit'),
    path('<id>/delete/',views.RecordDetailDelete.as_view(),name='record_detail_delete'),

]

person/views.py
from django.shortcuts import HttpResponse,render_to_response,HttpResponseRedirect
from django.views.generic import TemplateView,ListView,DetailView,CreateView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy,reverse
from accounts.models import User,UserProfile,UserBelong
from django.http import Http404, HttpResponseBadRequest
from django.contrib.auth.decorators import login_required
from records.models import UserRecordContent

class Home(LoginRequiredMixin,ListView):
    """レコードリスト ホーム"""
    template_name = 'person/home.html'
    paginate_by = 6
    context_object_name = 'records'

    def get_queryset(self):
      user = self.request.user
      try:
        group = UserBelong.objects.get(user=user, approval=1).group
        return UserRecordContent.objects.filter(group=group, )
      except:
        #所属がなければ投稿データのみを取得
        return UserRecordContent.objects.filter(user=self.request.user)


class MyAccount(LoginRequiredMixin,ListView):
    """ログインユーザーアカウント"""
    template_name = 'person/myaccount.html'

    def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      user = self.kwargs.get('username')
      try:#groupに所蔵しているか
        context['groups'] = UserBelong.objects.select_related('user').get(user__username=user).group
      except UserBelong.DoesNotExist:
        pass
      try:#Recordを投稿しているか
        context['count'] = UserRecordContent.objects.select_related('user').filter(user__username=user).count()
      except UserRecordContent.DoesNotExist:
        pass
      context['username'] = user
      context['image'] = UserProfile.objects.select_related('user').get(user__username=user).user_image
      return context

    def get_queryset(self):
      user = self.kwargs.get('username')
      try:
        return UserRecordContent.objects.select_related('user').filter(user__username=user)
      except UserRecordContent.DoesNotExist:
        return



class Menbers(LoginRequiredMixin,ListView):
    """同じグループの所属一覧"""
    template_name = 'person/members.html'
    model = User
    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super(Menbers,self).get_context_data(**kwargs)
        context_data['approval'] = UserProfile.objects.filter(
          user__user_profile__group__userbelong__user=self.request.user.user_id,
          user__user_profile__approval=True
        )
        context_data['unapproved'] = UserProfile.objects.filter(
          user__user_profile__group__userbelong__user=self.request.user.user_id,
          user__user_profile__approval=False
        )

        return context_data

@login_required
def member_approval(request):
    """メンバーの承認ページ"""
    user = request.POST.get('user')
    belong_model = UserBelong.objects.get(user__user_profile__user__username=user)
    belong_model.approval = True
    belong_model.save()
    return HttpResponseRedirect(reverse('person:members'))


class Agreement(TemplateView):
  template_name = 'person/agreement.html'

templates/person/agreement.html
<div class="wrapHINAGATA">
<h1>利用規約</h1>
<p>この利用規約（以下，「本規約」といいます。）は，＿＿＿＿＿（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。</p>

<h2>第1条（適用）</h2>
<ol>
<li>本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。</li>
<li>当社は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。</li>
<li>本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。</li>
</ol>

<h2>第2条（利用登録）</h2>
<ol>
<li>本サービスにおいては，登録希望者が本規約に同意の上，当社の定める方法によって利用登録を申請し，当社がこれを承認することによって，利用登録が完了するものとします。</li>
<li>当社は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。
<ol>
<li>利用登録の申請に際して虚偽の事項を届け出た場合</li>
<li>本規約に違反したことがある者からの申請である場合</li>
<li>その他，当社が利用登録を相当でないと判断した場合</li>
</ol></li>
</ol>

<h2>第3条（ユーザーIDおよびパスワードの管理）</h2>
<ol>
<li>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。</li>
<li>ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。当社は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</li>
<li>ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，当社に故意又は重大な過失がある場合を除き，当社は一切の責任を負わないものとします。</li>
</ol>

<h2>第4条（利用料金および支払方法）</h2>
<ol>
<li>ユーザーは，本サービスの有料部分の対価として，当社が別途定め，本ウェブサイトに表示する利用料金を，当社が指定する方法により支払うものとします。</li>
<li>ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年14．6％の割合による遅延損害金を支払うものとします。</li>
</ol>

<h2>第5条（禁止事項）</h2>
<p>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</p>

<ol>
<li>法令または公序良俗に違反する行為</li>
<li>犯罪行為に関連する行為</li>
<li>本サービスの内容等，本サービスに含まれる著作権，商標権ほか知的財産権を侵害する行為</li>
<li>当社，ほかのユーザー，またはその他第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
<li>本サービスによって得られた情報を商業的に利用する行為</li>
<li>当社のサービスの運営を妨害するおそれのある行為</li>
<li>不正アクセスをし，またはこれを試みる行為</li>
<li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
<li>不正な目的を持って本サービスを利用する行為</li>
<li>本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為</li>
<li>他のユーザーに成りすます行為</li>
<li>当社が許諾しない本サービス上での宣伝，広告，勧誘，または営業行為</li>
<li>面識のない異性との出会いを目的とした行為</li>
<li>当社のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
<li>その他，当社が不適切と判断する行為</li>
</ol>

<h2>第6条（本サービスの提供の停止等）</h2>
<ol>
<li>当社は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
<ol>
<li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
<li>地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</li>
<li>コンピュータまたは通信回線等が事故により停止した場合</li>
<li>その他，当社が本サービスの提供が困難と判断した場合</li>
</ol></li>
<li>当社は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。</li>
</ol>

<h2>第7条（利用制限および登録抹消）</h2>
<ol>
<li>当社は，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。
<ol>
<li>本規約のいずれかの条項に違反した場合</li>
<li>登録事項に虚偽の事実があることが判明した場合</li>
<li>料金等の支払債務の不履行があった場合</li>
<li>当社からの連絡に対し，一定期間返答がない場合</li>
<li>本サービスについて，最終の利用から一定期間利用がない場合</li>
<li>その他，当社が本サービスの利用を適当でないと判断した場合</li>
</ol></li>
<li>当社は，本条に基づき当社が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</li>
</ol>

<h2>第8条（退会）</h2>
<p>ユーザーは，当社の定める退会手続により，本サービスから退会できるものとします。</p>

<h2>第9条（保証の否認および免責事項）</h2>
<ol>
<li>当社は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</li>
<li>当社は，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する当社とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。</li>
<li>前項ただし書に定める場合であっても，当社は，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当社またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。</li>
<li>当社は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</li>
</ol>

<h2>第10条（サービス内容の変更等）</h2>
<p>当社は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。</p>

<h2>第11条（利用規約の変更）</h2>
<p>当社は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。</p>

<h2>第12条（個人情報の取扱い）</h2>
<p>当社は，本サービスの利用によって取得する個人情報については，当社「プライバシーポリシー」に従い適切に取り扱うものとします。</p>

<h2>第13条（通知または連絡）</h2>
<p>ユーザーと当社との間の通知または連絡は，当社の定める方法によって行うものとします。当社は,ユーザーから,当社が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。</p>

<h2>第14条（権利義務の譲渡の禁止）</h2>
<p>ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</p>

<h2>第15条（準拠法・裁判管轄）</h2>
<ol>
<li>本規約の解釈にあたっては，日本法を準拠法とします。</li>
<li>本サービスに関して紛争が生じた場合には，当社の本店所在地を管轄する裁判所を専属的合意管轄とします。</li>
</ol>

<p class="tR">以上</p>


</div><!--／wrapHINAGATA-->
</div><!--／wrapKOPIPE-->

templates/person/home.html
{% extends "commons/base.html" %}
{% load static %}

{% block title %}メニュー{% endblock %}

{% block headertitle %}{% endblock %}

{% block content %}

        <!-- Three columns of text below the carousel -->
{% for item in records %}
        {% if forloop.counter|add:"-1"|divisibleby:"2" or forloop.first %}
        <div class="row">
        {% endif %}
          <div class="col-lg-6 col-md-12 mt-5 col-sm-12  mx-auto">
          <div class="card">
            <img class="card-img-top" src="{{ item.user_record_image.url }}" alt="Generic placeholder image" width="200" height="200">
            <div class="card-body text-center">
              <a class="btn text-dark" href="{% url 'records:record_detail' item.id %}" role="button">
              <h2>{{ item.user }}</h2>
              <p>{{ item.user_record_content }}</p>
              {% if userrecordcontent.user_record_title  %}
              <p>{{ userrecordcontent.user_record_title }}</p>
              {% endif %}
              <small class="text-muted">{{ item.user_record_elapsed_time }}</small>
              <small class="text-muted">{{ item.user_record_time }}</small>
              </a>
            </div>
          </div><!-- /.col-lg-4 -->
        </div>
        {% if forloop.counter|divisibleby:"2" or forloop.last %}
        </div>
        {% endif %}
        {% empty %}
            <div class="jumbotron bg-light text-muted">
        <h1 class="h3">グループでレコードを共有しよう！</h1>
        <p class="lead">メンバー</p>
        <a class="btn text-white bg-dark" href="{% url 'records:recordcreate' %}" role="button">早速作ってみる</a>
      </div>
{% endfor %}
<ul class="pagination mt-2">
    <!-- 前へ の部分 -->
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
    {% endif %}

    <!-- 数字の部分 -->
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
    {% endfor %}

    <!-- 次へ の部分 -->
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    {% endif %}
</ul>
{% endblock %}

{% block scripts %}
{% endblock %}

templates/person/member_approval.html
{% extends "commons/base.html" %}
{% load static %}

{% block title %}プロフィールフォーム{% endblock %}
{% block content %}
<form method="POST" action="">
  <div class ="text-center col-lg-7 mx-auto col-md-6 col-sm-7 col-8">
    {% csrf_token %}
    <div class="form-group">
    <p>本当に "{{ object }}" を承認しますか?</p>
      </div>

    <input class="btn btn-light" type="submit" value="submit">
  </div>
</form>

{% endblock %}

templates/person/members.html
{% extends "commons/base.html" %}
{% load static %}
{% block title %}メニュー{% endblock %}

{% block headertitle %} MEMBERS{% endblock %}

{% block content %}
<div class="container marketing renewlist" role="main">
  <div class="">
  <div class="mb-4 border-bottom">
    <h1 class="h4 lead font-weight-bold">members</h1>
      </div>
  <div class="">

        {% for item in  approval %}
        {% if forloop.counter|add:"-1"|divisibleby:"4" or forloop.first %}
        <div class="row">
        {% endif %}

          <div class="col-lg-3 col-md-4 col-sm-6 mx-auto">
            <div class="text-center">
            <a class="btn text-dark" href="{% url 'person:myaccount' username=item.user %}" role="button">
              <img class="rounded-circle" src="{{ item.user_image.url }}" alt="Generic placeholder image" width="140" height="140">
            <div class="card-body">
              <h2>{{ item.user }}</h2>
            {% if item.position %}
                 {{ item.position }}
                {% endif %}
            {% if item.sports_position %}
                    {{ item.suports_position }}
                {% endif %}
            {% if item.school_year %}
                    {{ item.school_year }}
                {% endif %}
              </div>
              </a>
            </div>
          </div>
          {% if forloop.counter|divisibleby:"4" or forloop.last %}
        </div>
        {% endif %}
          {% endfor %}
    </div>
</div>
  <div class="">
    <div class="mb-4 border-bottom">
    <h1 class="h4 lead font-weight-bold">approval</h1>
      <small>承認後の取り消しはできませんのでご注意ください。</small>
      </div>
<div class="">
          {% for item in  unapproved %}
          {% if forloop.counter|add:"-1"|divisibleby:"4" or forloop.first %}
        <div class="row">
        {% endif %}

          <div class="col-lg-3 col-md-4 col-sm-6 mx-auto">
            <div class="text-center">
            <a class="btn text-dark" href="{% url 'person:myaccount' username=item.user %}" role="button">
              <img class="rounded-circle" src="{{ item.image.url }}" alt="Generic placeholder image" width="140" height="140">
            <div class="card-body">
              <h2>{{ item.user }}</h2>
            {% if item.position %}
                 {{ item.position }}
                {% endif %}
            {% if item.sports_position %}
                    {{ item.suports_position }}
                {% endif %}
            {% if item.school_year %}
                    {{ item.school_year }}
                {% endif %}
              </div>
              </a>
              <form action="{% url 'person:member_approval' %}" method="post">
                {% csrf_token %}
                <input hidden name="user" value="{{ item.user }}">
              <button class="btn btn-light" >承認する</button>
              </form>
            </div>
          </div>
          {% if forloop.counter|divisibleby:"4" or forloop.last %}
        </div>
        {% endif %}
          {% endfor %}

    </div>
    </div>
</div>

{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="{% static 'person/js/member_approval.js' %}"></script>
{% endblock %}

templates/person/myaccount.html
{% extends "commons/base.html" %}

{% block title %}アカウント{% endblock %}

{% block headertitle %} ACCOUNTS{% endblock %}

{% block content %}

    <div class="row">
  		<div class="col-lg-4 col-sm-4 text-center">
        <img class="rounded-circle" src="{{ image.url }}" alt="Generic placeholder image" width="140" height="140">
      </div>

      <div class="col-lg-8">
        <div class="row">
          <div class="col-md-8">
            <h1 class="h3">{{ username }}</h1>
            <h2 class="h5 mx-auto">投稿{{ count }}件</h2>
          </div>
        </div>
          <div class="row">
            <div class="col-md-3 col-sm-4">
              {% if username == user.username %}
            <button type="button" onclick="location.href='{% url 'accounts:edit' %}'" class="btn btn-light text-right">プロフィールを編集する</button>
            {% endif %}
            </div>
            <div class="col-md-9">
              <h2>{{ group }}</h2>
            </div>
          </div>
        <div class="row">
        </div>
      </div>
    </div>

{% for item in object_list %}
{% if forloop.counter|add:"-1"|divisibleby:"2" or forloop.first %}
  <div class="row">
{% endif %}
    <div class=" col-lg-6 col-md-12 mt-5 col-sm-12">
      <div class="card mx-auto">
        <img class="card-img-top" height="180" src="{{ item.user_record_image.url }}" alt="Card image cap">
        <div class="card-body text-center">
         <a class="btn text-dark" href="{% url 'records:record_detail' item.id %}">
          <h4 class="card-title">{{ item.user_record_content }}</h4>
           {% if item.user_record_title  %}
              <p class="card-text">{{ item.user_record_title }}</p>
              {% endif %}
           </a>
        </div>
      </div><!-- /.col-lg-4 -->
    </div>


    {% if forloop.counter|divisibleby:"2" or forloop.last %}
  </div>
{% endif %}
  {% endfor %}
{% if user.is_authenticated %}

{% endif %}
{% endblock %}

{% block scripts %}
{% endblock %}