groups/urls.py
from django.urls import path
from . import views


app_name = 'groups'

urlpatterns = [
    path('',views.GroupList.as_view(),name='group_list'),#部活動メンバーの一覧表示
    path('ajax_post_add/',views.GroupRequestAdd,name='ajax_post_add'),
    path('<str:group_id>/request/',views.GroupDetail.as_view(),name='group_detail'),
    path('create/',views.GroupCreate.as_view(),name='group_create')
]

person/urls.py
from django.urls import path,include
from . import views


app_name = 'person'

urlpatterns = [
    path('',views.Home.as_view(),name='home'),#部活動メンバーの一覧表示
    path('<slug:username>/myaccount/', views.MyAccount.as_view(), name='myaccount'),  # 該当アカウント
    path('members/', views.Menbers.as_view(), name='members'),  # members
    path('members/approval/',views.member_approval,name='member_approval'),
    path('agreement/',views.Agreement.as_view(),name='agreement'),
]

person_manager/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
import person



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('person.urls')),
    path('accounts/', include('accounts.urls')),
    path('records/',include('records.urls')),
    path('schedules/',include('schedules.urls')),
    path('groups/',include('groups.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

records/urls.py
from django.urls import path,include
from . import views


app_name = 'records'

urlpatterns = [
    path('recordcreate/',views.RecordCreate.as_view(),name='recordcreate'),
    path('title_create/',views.title_create,name='title_create'),
    path('<id>/', views.RcordDetail.as_view(), name='record_detail'),
    path('<id>/edit/', views.RecordDetailEdit.as_view(), name='record_detail_edit'),
    path('<id>/delete/',views.RecordDetailDelete.as_view(),name='record_detail_delete'),

]

schedules/urls.py
from django.urls import path
from . import views

app_name = 'schedules'

urlpatterns = [
    path('', views.MonthCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
]

templates/commons/account_base.html
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <meta name="description" content="部活がこんなに楽しく!?●●を使って部活を快適に楽しもう！">
    <title>
      {% block title %}{% endblock %}
    </title>

  <link rel="stylesheet" href="{% static 'commons/css/account_base.css' %}">
    {% block link %}{% endblock %}
    </head>

<body>

<div class="container mb-5" role="main">
{% block content %}{% endblock %}
</div>

{% block extrajs %}{% endblock %}

</body>
</html>

templates/commons/base.html
{% load static %}
{% load person_extras %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load widget_tweaks %}


<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <meta name="description" content="部活がこんなに楽しく!?●●を使って部活を快適に楽しもう！">
    <title>
      {% block title %}{% endblock %}
    </title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'commons/css/base.css' %}">
    {% block link %}{% endblock %}
    </head>

<body>

<header>
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'person:home' %}">APASN{% block headertitle %}{% endblock %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'person:myaccount' username=user.username %}">アカウント</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'schedules:month' %}">カレンダー</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'records:recordcreate' %}">レコード</a>

        </li>

        <li class="nav-item">
           {% if user|belong_judgment %}
          <a class="nav-link" href="{% url 'person:members' %}">メンバー</a>
           {% else %}
          <a class="nav-link" href="{% url 'groups:group_list' %}">グループ</a>
          {% endif %}

        </li>
      </ul>
    </div>
  </div>
</nav>
</header>

<div class="container content mb-5" role="main">
{% block content %}{% endblock %}
</div>


<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class=" text-center">
      <small>© 2019 person</small>
    </div>
  </footer>
{% block extrajs %}{% endblock %}

</body>
</html>